### ISSUE TITLE
Node and NPM are installed. Cannot install Power Pages generator: Error: spawnSync npm.cmd EINVAL

### ISSUE THREAD

**Issue by sethjenners** [microsoft/powerplatform-vscode#1018]
![Error](https://github.com/user-attachments/assets/02c00ab5-63c0-4f5e-b92d-8d634457e86f)
![NodeInstalled](https://github.com/user-attachments/assets/8d3aba0c-ef37-47d1-975b-42549e9ea3e3)

Do you have any advice on how to fix this error?

**Comment by gigasean80** [comment]
I am facing the same issue, is there any info on this?

**Comment by kevinhuizer** [comment]
I have the same issue, also with a fresh install of VSCode and modules.

**Comment by iddycol** [comment]
Same issue here - fresh installs and latest versions. Any Thoughts?

**Comment by brad-house** [comment]
Same issue as well. Running node v22.9.0 and npm 10.8.3.

**Comment by iddycol** [comment]
I think this is caused by security fixes (breaking changes) that were applied to Node.js

**Comment by brad-house** [comment]
I've tried a few different configurations now.  So far I'm still getting the same error.

**Node.js**
22.9.0
20.18.0
18.20.4
17.9.1

**Power Platform Tools Extension**
2.0.66
2.0.63
2.0.49
2.0.72 (pre-release)

Nothing has worked so far.

**Comment by amitjoshi438** [comment]
Correct @iddycol, it's caused due to that update only:

[security update](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high) 

From that blog:
It is important to note that there has been a breaking change for Windows users who utilize child_process.spawn and child_process.spawnSync. Node.js will now error with EINVAL if a .bat or .cmd file is passed to child_process.spawn and child_process.spawnSync without the shell option set. If the input to spawn/spawnSync is sanitized, users can now pass { shell: true } as an option to prevent the occurrence of EINVALs errors.

Fixed will be released soon.

**Comment by tyaginidhi** [comment]
Fixed with 2.0.74: https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.powerplatform-vscode&ssr=false#version-history

**Comment by brad-house** [comment]
Just installed the updated extension and confirmed that the but is fixed.

Thanks!!!!
