### ISSUE TITLE
Can't Create CDS Authentication account through PowerApps CLI

### ISSUE THREAD

**Issue by fadyyeta** [microsoft/powerplatform-vscode#109]
Trying to create a CDS --kind Authentication through PAC and gives me this error

Error: Failed to connect to Dataverse
There was no endpoint listening at https://< organization-URL >.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.46.3082 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
The remote server returned an error: (407) Proxy Authentication Required.

Our environment is accessing dynamics through a proxy that is installed properly.
I am able to perform other tasks of PAC such as create --kind ADMIN or create a Backup of environment.

In Azure we have an app registration that is pointing at the enterprise application Dynamics CRM and it has user-impersonation with admin consent

**Comment by davidjenni** [comment]
@fadyyeta the error to not be able to connect to Dataverse is caused by your local network that requires proxy authN:
``` The remote server returned an error: (407) Proxy Authentication Required.```

The Dataverse service client that is used by pac CLI has no support for handling local proxy authentication; before trying to connect via pac CLI to your Dataverse environments, ensure that your PC has authenticated to your network's internet proxy, e.g. via browser. 
This behavior is currently by design, with no backlog work items to address this

**Comment by mannybellas** [comment]
@fadyyeta I have also come across this issue, but when using pac via CLI.  To fix this I added the following to the configuration section of `pac.exe.config` file :

```
<system.net>
	<defaultProxy useDefaultCredentials="true" enabled="true"></defaultProxy>
</system.net>
```
The pac.exe.config for me was located in the Microsoft.PowerApps.CLI.1.9.4\tools subdirectory of the pac installation location.

Hope this helps.
