### ISSUE TITLE
Backup Label and Notes doesn't do anything

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-vscode#181]
While taking backup of the environment, even though when you past label value it doesn't get reflected in the actual backup instead it displays the time when the backup was taken. 

To repo:
- authenticate through pac auth with user credential who has SA rights to the environment
- pac admin backup -env 'environment-url-where-you-want-to-take-backup' -l 'backup-from-pac-cli'

Once complete, 
- go to Power Platform Admin center 
- open the envrironment which you choose to take backup of,
- select Backups > Restore or manage
- Select 'Manual'

Expected: you should see backup with label 'backup-from-pac-cli'
Actual: you will see backup with label 'date + time when the backup was taken'

**Comment by davidjenni** [comment]
@sanjeev40084 this is unfortunately by design: the Backup labels and notes fields have been deprecated in PPAC already, since the underlying PowerPlatform environment management API deprecates those 2 fields.

We will mark the notes and the labels parameters in the pac CLI as deprecated as well, but will not remove them. Setting them will only cause a warning message that any assigned value is ignored
