### ISSUE TITLE
Non-recoverable error, terminated

### ISSUE THREAD

**Issue by tech-steph** [microsoft/powerplatform-vscode#183]
CMD:
`pac canvas unpack --msapp <PATH>`

Result:
`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 1d90342e-e1d1-445f-96a2-6103cfd90015, Exception Type: System.ArgumentException`

Comments:
The application looks to be unpacked in the explorer. Assets, Entropy, pkgs, Src all created. However due to "non recoverable error", unpack msapp files step in Azure DevOps Pipelines errors out entire pipeline.

**Comment by tehcrashxor** [comment]
Tracked as AB#2669139

**Comment by davidjenni** [comment]
@tech-steph 
Underlying issue was fixed in microsoft/PowerApps-Language-Tooling#381
The resulting PALT nuget pkg 0.4.3 with this fix has already been added to the pac CLI's main branch. It will ship as part of the next April monthly refresh, ETA early/mid May at the latest

CC: @tomjschneider @tehcrashxor
