### ISSUE TITLE
Downloading code from a PowerApps website and overwriting causes CLI to crash 

### ISSUE THREAD

**Issue by genaro56** [microsoft/powerplatform-vscode#203]
I'm experimenting with this tool to use with my team and wanted to start developing without using the in-built power platform editor, so when I download changes from the power apps website I want to overwrite the files by adding the flag: `--overwrite` but the CLI crashes. See screenshot below 
---
![image](https://user-images.githubusercontent.com/36680368/171478458-ad569bec-2f7e-4f06-bbe2-0de74c64de10.png)

`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 201e83d1-ee78-46b7-b8f4-2d97cf68c432, Exception Type: System.FormatExceptionThe diagnostic logs can be found at: c:\Users\gemartinez\AppData\Roaming\Code\User\globalStorage\microsoft-isvexptools.powerplatform-vscode\pac\tools\logs\pac-log.txt`

**Comment by tehcrashxor** [comment]
It looks like the overwrite argument was not implemented as a switch -- i.e. it actually requires a value (`--overwrite true` or `-o true`) instead of resolving as true just from the presence of the argument.

So @genaro56, you should be able to run successfully by fully specifying `-o true`.

That being said, looks like we have two issues to work on here:
1) consider swapping the `overwrite` parameter to a switch type 
2) better error messaging when the parameter is in an unexpected format instead of the unhandled "Sorry, the app encountered a non recoverable error..." message.

**Comment by tehcrashxor** [comment]
Tracking the parameter-as-a-switch work as AB#2745132
Tracking the bad error handling/messaging as AB#2745136

**Comment by tehcrashxor** [comment]
The switch logic fix has been rolled out with PAC v1.16.6 / powerplatform-vscode v1.0.16  in #216
