### ISSUE TITLE
Why does this extension always activate?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/powerplatform-vscode#228]
can you tell me why this extension needs to be activated for:

* `onStartupFinished`
* `onLanguage:yaml`
* `onLanguage:html`

From my perspective, this extension isn't going to be used all the time to warrant these events and an extension activating when it shouldn't need to ends up annoying customers and impacts performance.

**Comment by ashishchoudhary001** [comment]
Hey Tyler,
Thanks for pointing this out. 
The onLanguage activation events are required by our extension since we support custom AutoComplete in yaml and html files (this autocomplete does not interfere with the language's default autocomplete).
I am not very sure about the 'onStartupFinished' event. I will check with the team and will update about it.

@tehcrashxor @davidjenni can you please answer about why do we need 'onStartupFinished' event.

**Comment by TylerLeonhardt** [comment]
> since we support custom AutoComplete in yaml and html files

Does this apply to all YAML & HTML files or is there a common file name for Power Portal files where the [workspaceContains](https://code.visualstudio.com/api/references/activation-events#workspaceContains) activation event would be more accurate?

**Comment by davidjenni** [comment]
@TylerLeonhardt isn't the `onStartupFinished` [activation off the critical path](https://vscode-westeu.azurewebsites.net/api/references/activation-events#onStartupFinished), i.e. vscode calls it delayed? Our activate event handler mostly just does setup subscriptions to hook into the host's events.

The one potentially expensive work is unzipping a .nupkg with our pac CLI; but that extra work only happens if a newer .vsix also contains a newer version of our .nupkg. In startups after that, it should be cheaper.
The onLanguage hooks are as @ashishchoudhary001 already elaborated; I suppose that part could switch to workspaceContains?

Since you're on the vscode team, I'd be happy to have a conversation via corporate Teams, pls add @tehcrashxor, @ashishchoudhary001 (in IST timezon) and myself to that convo.
