### ISSUE TITLE
Renaming Auth profile: textbox length too short

### ISSUE THREAD

**Issue by mabrizi01** [microsoft/powerplatform-vscode#301]
![image](https://user-images.githubusercontent.com/24695165/193015052-74bf2482-df41-4eb5-a57e-673ef5d622a6.png)

It seems that 30 characters are too few to accept longer addresses. I'm not able to set-up an auth profile pointing to addresses like "https://mabrizi75-w1-cs.crm.dynamics.com/"

**Comment by davidjenni** [comment]
@mabrizi01 this is by design: Note that this is a menu to rename the *authentication profile* name, but it is NOT to rename the URL of the environment. Profile names are not urls but just short, human chosen names like "myDevTenant" or similar. The length of profiles is limited to 30 characters by the pac CLI itself.

CC: @tehcrashxor @swapnilbhalgat
