### ISSUE TITLE
unpack command unpacks my canvas app with error

### ISSUE THREAD

**Issue by KanmaniTMurugesan** [microsoft/powerplatform-vscode#315]
Unpacking canvas app and seems it has artefact where the PAC command line tools CLI does not support, or the PAC tool has a bug.

![image](https://user-images.githubusercontent.com/115699282/196097729-6dbfec88-d894-4824-afc0-f7b45e25bb00.png)

It says Roundrop validation on unpack failed. This is always a bug, please file an issue at ... (as in above image).

So even though a folder is generated and looks like a valid source code for loansearchproducts canvas app, the folder does not have integrity due to the error.
Consequently, when we perform the reverse operation i.e. pack the source folder into an msapp, it failed with error message, which is the same as the first one that we saw like

Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:6dc49459-b286-401e-b35c-4f67539ab94f.

Please help us!!!

**Comment by davidjenni** [comment]
@KanmaniTMurugesan You are using a fairly old version of pac CLI, v1.10.4 (published last December); the current published pac CLI from our September refresh is 1.19.4.
Over the past 9 months, the Canvas team has made many fixes, so odds are, your issue is addressed now?

If you installed the pac CLI via our VS Code extension, please ensure your "Power Platform Extension" is version *1.1.5* (see also release notes here: https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.powerplatform-vscode).

If you installed via our MSI, please run: `pac install latest` to ensure you're using 1.19.4

CC: @tomjschneider
