### ISSUE TITLE
Environment names containing Japanese characters are not displayed correctly

### ISSUE THREAD

**Issue by KazuhikoNakamoto** [microsoft/powerplatform-vscode#356]
Environment names containing Japanese characters are not displayed correctly

I have a PowerPlatform environment with display names set using Japanese.

Japanese is not displayed correctly in the VS Code tree view of environments and solutions.
When selecting an environment, the error message

Unexpected token in JSON at position xxx

is displayed.

![error](https://user-images.githubusercontent.com/118335970/202104035-c064a433-fd3b-423e-be91-88472a3f1e91.png)

**Comment by tehcrashxor** [comment]
Tracking internally as AB#3085166

The UI panel is based on the output of `pac.exe` running in the background with the command `pac org list`.   It looks like PAC correctly writes the data with UTF-8, and the extension is set to read the exe's stdout in UTF-8, but the symbol garbling is occurring _between_ those steps due to the NodeJS spawn mechanics using the OS's default shell, which for Windows in the Command Prompt.

Tested on two Linux boxes (WSL and GH CodeSpaces), and the text appears correct there:
![image](https://user-images.githubusercontent.com/3751389/206036290-90d1b4b3-9ced-4c97-8588-9f22a3b472c7.png)
Presumably this should work on Mac as well, but I don't currently have my test Mac nearby to check.

On Windows, I get the garbled output in the UI:
![image](https://user-images.githubusercontent.com/3751389/206036880-f8e1ae2b-a928-4063-98ff-85006fe5f23c.png)

Running the underlying `pac org list` works in PowerShell, but is garbled using the win Command Prompt:
![image](https://user-images.githubusercontent.com/3751389/206037465-a35878da-2e2c-45dd-85f9-ad2cc8438f2a.png)
![image](https://user-images.githubusercontent.com/3751389/206037820-245c36be-ec9a-4f5d-bfb7-c9004100e996.png)

**Comment by tehcrashxor** [comment]
Fixed in PAC v1.21.4+ and the VSCode Extension v1.1.14
